services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.136.0
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml:ro
      - /var/log/containers:/var/log/containers:ro
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - loki
      - tempo
      - mimir

  loki:
    image: grafana/loki:3.5.0
    command: ["-config.file=/etc/loki/config.yaml"]
    volumes:
      - ./loki-config.yaml:/etc/loki/config.yaml:ro
      - loki-data:/loki
    ports:
      - "3100:3100"

  tempo:
    image: grafana/tempo:2.8.2
    command: ["-config.file=/etc/tempo/config.yaml"]
    volumes:
      - ./tempo-config.yaml:/etc/tempo/config.yaml:ro
      - tempo-data:/var/tempo
    ports:
      - "3200:3200"
      - "4319:4317"
      - "4320:4318"

  mimir:
    image: grafana/mimir:2.17.0
    command: ["-target=all", "-config.file=/etc/mimir/config.yaml"]
    volumes:
      - ./mimir-config.yaml:/etc/mimir/config.yaml:ro
      - mimir-data:/data
    ports:
      - "9009:9009"

  grafana:
    image: grafana/grafana:12.0.2
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafana-data:/var/lib/grafana
    ports:
      - "3001:3000"
    depends_on:
      - loki
      - tempo
      - mimir

volumes:
  grafana-data:
  loki-data:
  mimir-data:
  tempo-data:
